# -*- coding: utf-8 -*-
"""Plan de conturi OMFP 1802/2014 - denumiri sintetice (fallback cand planul tenantului e gol).
Sursa: Reglementarile contabile OMFP 1802/2014, anexa - planul de conturi general."""

PLAN_OMFP = {
    "101": "Capital", "1012": "Capital subscris varsat", "105": "Rezerve din reevaluare",
    "106": "Rezerve", "1061": "Rezerve legale", "1068": "Alte rezerve",
    "117": "Rezultatul reportat", "1171": "Rezultatul reportat - profit nerepartizat / pierdere neacoperita",
    "121": "Profit sau pierdere", "129": "Repartizarea profitului",
    "151": "Provizioane", "161": "Imprumuturi din emisiuni de obligatiuni",
    "162": "Credite bancare pe termen lung", "1621": "Credite bancare pe termen lung",
    "166": "Datorii care privesc imobilizarile financiare",
    "167": "Alte imprumuturi si datorii asimilate", "168": "Dobanzi aferente imprumuturilor",
    "201": "Cheltuieli de constituire", "203": "Cheltuieli de dezvoltare",
    "205": "Concesiuni, brevete, licente, marci comerciale",
    "208": "Alte imobilizari necorporale",
    "211": "Terenuri si amenajari de terenuri", "212": "Constructii",
    "213": "Instalatii tehnice si mijloace de transport",
    "2131": "Echipamente tehnologice", "2132": "Aparate si instalatii de masurare",
    "2133": "Mijloace de transport", "214": "Mobilier, aparatura birotica",
    "231": "Imobilizari corporale in curs de executie",
    "261": "Actiuni detinute la entitatile afiliate", "267": "Creante imobilizate",
    "280": "Amortizari privind imobilizarile necorporale",
    "2805": "Amortizarea concesiunilor, brevetelor, licentelor",
    "2808": "Amortizarea altor imobilizari necorporale",
    "281": "Amortizari privind imobilizarile corporale",
    "2811": "Amortizarea amenajarilor de terenuri", "2812": "Amortizarea constructiilor",
    "2813": "Amortizarea instalatiilor si mijloacelor de transport",
    "2814": "Amortizarea altor imobilizari corporale",
    "301": "Materii prime", "302": "Materiale consumabile", "3021": "Materiale auxiliare",
    "3022": "Combustibili", "3024": "Piese de schimb", "3028": "Alte materiale consumabile",
    "303": "Materiale de natura obiectelor de inventar",
    "331": "Produse in curs de executie", "345": "Produse finite",
    "371": "Marfuri", "378": "Diferente de pret la marfuri",
    "381": "Ambalaje", "391": "Ajustari pentru deprecierea materiilor prime",
    "397": "Ajustari pentru deprecierea marfurilor",
    "401": "Furnizori", "403": "Efecte de platit", "404": "Furnizori de imobilizari",
    "408": "Furnizori - facturi nesosite", "409": "Furnizori - debitori",
    "4091": "Furnizori - debitori pentru cumparari de bunuri",
    "411": "Clienti", "4111": "Clienti", "4118": "Clienti incerti sau in litigiu",
    "413": "Efecte de primit de la clienti", "418": "Clienti - facturi de intocmit",
    "419": "Clienti - creditori",
    "421": "Personal - salarii datorate", "423": "Personal - ajutoare materiale datorate",
    "425": "Avansuri acordate personalului", "426": "Drepturi de personal neridicate",
    "427": "Retineri din salarii datorate tertilor",
    "428": "Alte datorii si creante in legatura cu personalul",
    "431": "Asigurari sociale", "4315": "Contributia de asigurari sociale",
    "4316": "Contributia de asigurari sociale de sanatate",
    "436": "Contributia asiguratorie pentru munca",
    "437": "Ajutor de somaj", "438": "Alte datorii si creante sociale",
    "441": "Impozitul pe profit si alte impozite", "4411": "Impozitul pe profit",
    "4418": "Impozitul pe venit",
    "442": "Taxa pe valoarea adaugata", "4423": "TVA de plata", "4424": "TVA de recuperat",
    "4426": "TVA deductibila", "4427": "TVA colectata", "4428": "TVA neexigibila",
    "444": "Impozitul pe venituri de natura salariilor",
    "445": "Subventii", "446": "Alte impozite, taxe si varsaminte asimilate",
    "447": "Fonduri speciale - taxe si varsaminte asimilate",
    "448": "Alte datorii si creante cu bugetul statului",
    "455": "Sume datorate actionarilor/asociatilor",
    "4551": "Actionari/asociati - conturi curente",
    "456": "Decontari cu actionarii/asociatii privind capitalul",
    "457": "Dividende de plata", "458": "Decontari din operatiuni in participatie",
    "461": "Debitori diversi", "462": "Creditori diversi",
    "471": "Cheltuieli inregistrate in avans", "472": "Venituri inregistrate in avans",
    "473": "Decontari din operatiuni in curs de clarificare",
    "491": "Ajustari pentru deprecierea creantelor - clienti",
    "5121": "Conturi la banci in lei", "5124": "Conturi la banci in valuta",
    "5125": "Sume in curs de decontare", "512": "Conturi curente la banci",
    "518": "Dobanzi", "519": "Credite bancare pe termen scurt",
    "531": "Casa", "5311": "Casa in lei", "5314": "Casa in valuta",
    "532": "Alte valori", "5328": "Alte valori",
    "541": "Acreditive", "542": "Avansuri de trezorerie",
    "581": "Viramente interne",
    "601": "Cheltuieli cu materiile prime", "602": "Cheltuieli cu materialele consumabile",
    "6021": "Cheltuieli cu materialele auxiliare", "6022": "Cheltuieli privind combustibilii",
    "6024": "Cheltuieli privind piesele de schimb", "6028": "Cheltuieli privind alte materiale consumabile",
    "603": "Cheltuieli privind materialele de natura obiectelor de inventar",
    "604": "Cheltuieli privind materialele nestocate",
    "605": "Cheltuieli privind utilitatile", "607": "Cheltuieli privind marfurile",
    "608": "Cheltuieli privind ambalajele",
    "611": "Cheltuieli cu intretinerea si reparatiile",
    "612": "Cheltuieli cu redeventele, locatiile de gestiune si chiriile",
    "613": "Cheltuieli cu primele de asigurare", "614": "Cheltuieli cu studiile si cercetarile",
    "621": "Cheltuieli cu colaboratorii", "622": "Cheltuieli privind comisioanele si onorariile",
    "623": "Cheltuieli de protocol, reclama si publicitate",
    "624": "Cheltuieli cu transportul de bunuri si personal",
    "625": "Cheltuieli cu deplasari, detasari si transferari",
    "626": "Cheltuieli postale si taxe de telecomunicatii",
    "627": "Cheltuieli cu serviciile bancare si asimilate",
    "628": "Alte cheltuieli cu serviciile executate de terti",
    "635": "Cheltuieli cu alte impozite, taxe si varsaminte asimilate",
    "641": "Cheltuieli cu salariile personalului",
    "642": "Cheltuieli cu avantajele in natura si tichetele acordate salariatilor",
    "645": "Cheltuieli privind asigurarile si protectia sociala",
    "646": "Cheltuieli privind contributia asiguratorie pentru munca",
    "652": "Cheltuieli cu protectia mediului inconjurator",
    "654": "Pierderi din creante si debitori diversi",
    "655": "Cheltuieli din reevaluarea imobilizarilor corporale",
    "658": "Alte cheltuieli de exploatare", "6581": "Despagubiri, amenzi si penalitati",
    "6588": "Alte cheltuieli de exploatare",
    "665": "Cheltuieli din diferente de curs valutar", "666": "Cheltuieli privind dobanzile",
    "667": "Cheltuieli privind sconturile acordate",
    "681": "Cheltuieli de exploatare privind amortizarile, provizioanele",
    "6811": "Cheltuieli de exploatare privind amortizarea imobilizarilor",
    "6812": "Cheltuieli de exploatare privind provizioanele",
    "6814": "Cheltuieli de exploatare privind ajustarile pentru deprecierea activelor circulante",
    "691": "Cheltuieli cu impozitul pe profit", "698": "Cheltuieli cu impozitul pe venit",
    "701": "Venituri din vanzarea produselor finite", "704": "Venituri din servicii prestate",
    "705": "Venituri din studii si cercetari", "706": "Venituri din redevente, locatii de gestiune si chirii",
    "707": "Venituri din vanzarea marfurilor", "708": "Venituri din activitati diverse",
    "711": "Venituri aferente costurilor stocurilor de produse",
    "721": "Venituri din productia de imobilizari necorporale",
    "722": "Venituri din productia de imobilizari corporale",
    "741": "Venituri din subventii de exploatare",
    "754": "Venituri din creante reactivate si debitori diversi",
    "758": "Alte venituri din exploatare", "7581": "Venituri din despagubiri, amenzi si penalitati",
    "7588": "Alte venituri din exploatare",
    "765": "Venituri din diferente de curs valutar", "766": "Venituri din dobanzi",
    "767": "Venituri din sconturi obtinute",
    "781": "Venituri din provizioane si ajustari pentru depreciere",
    "7814": "Venituri din ajustari pentru deprecierea activelor circulante",
    "8051": "Dobanzi de platit",
}


def denumire_omfp(cont):
    """Denumirea OMFP pentru un simbol de cont; cadere pe sinteticul de 3 cifre; '' daca necunoscut."""
    c = str(cont or "").strip()
    if c in PLAN_OMFP:
        return PLAN_OMFP[c]
    if len(c) > 3 and c[:4] in PLAN_OMFP:
        return PLAN_OMFP[c[:4]]
    if len(c) >= 3 and c[:3] in PLAN_OMFP:
        return PLAN_OMFP[c[:3]]
    return ""
