# -*- coding: utf-8 -*-
"""Plan de conturi OMFP 1802/2014 - denumiri sintetice (fallback cand planul tenantului e gol).
Sursa: Reglementarile contabile OMFP 1802/2014, anexa - planul de conturi general."""

PLAN_OMFP = {
    "101": "Capital", "1012": "Capital subscris vărsat", "105": "Rezerve din reevaluare",
    "106": "Rezerve", "1061": "Rezerve legale", "1068": "Alte rezerve",
    "117": "Rezultatul reportat", "1171": "Rezultatul reportat - profit nerepartizat / pierdere neacoperită",
    "121": "Profit sau pierdere", "129": "Repartizarea profitului",
    "151": "Provizioane", "161": "Împrumuturi din emisiuni de obligațiuni",
    "162": "Credite bancare pe termen lung", "1621": "Credite bancare pe termen lung",
    "166": "Datorii care privesc imobilizările financiare",
    "167": "Alte împrumuturi și datorii asimilate", "168": "Dobânzi aferente împrumuturilor",
    "201": "Cheltuieli de constituire", "203": "Cheltuieli de dezvoltare",
    "205": "Concesiuni, brevete, licențe, mărci comerciale",
    "208": "Alte imobilizări necorporale",
    "211": "Terenuri și amenajări de terenuri", "212": "Construcții",
    "213": "Instalații tehnice și mijloace de transport",
    "2131": "Echipamente tehnologice", "2132": "Aparate și instalații de măsurare",
    "2133": "Mijloace de transport", "214": "Mobilier, aparatură birotică",
    "231": "Imobilizări corporale în curs de execuție",
    "261": "Acțiuni deținute la entitățile afiliate", "267": "Creanțe imobilizate",
    "280": "Amortizări privind imobilizările necorporale",
    "2805": "Amortizarea concesiunilor, brevetelor, licențelor",
    "2808": "Amortizarea altor imobilizări necorporale",
    "281": "Amortizări privind imobilizările corporale",
    "2811": "Amortizarea amenajărilor de terenuri", "2812": "Amortizarea construcțiilor",
    "2813": "Amortizarea instalațiilor și mijloacelor de transport",
    "2814": "Amortizarea altor imobilizări corporale",
    "301": "Materii prime", "302": "Materiale consumabile", "3021": "Materiale auxiliare",
    "3022": "Combustibili", "3024": "Piese de schimb", "3028": "Alte materiale consumabile",
    "303": "Materiale de natura obiectelor de inventar",
    "331": "Produse în curs de execuție", "345": "Produse finite",
    "371": "Mărfuri", "378": "Diferențe de preț la mărfuri",
    "381": "Ambalaje", "391": "Ajustări pentru deprecierea materiilor prime",
    "397": "Ajustări pentru deprecierea mărfurilor",
    "401": "Furnizori", "403": "Efecte de plătit", "404": "Furnizori de imobilizări",
    "408": "Furnizori - facturi nesosite", "409": "Furnizori - debitori",
    "4091": "Furnizori - debitori pentru cumpărări de bunuri",
    "411": "Clienți", "4111": "Clienți", "4118": "Clienți incerți sau în litigiu",
    "413": "Efecte de primit de la clienți", "418": "Clienți - facturi de întocmit",
    "419": "Clienți - creditori",
    "421": "Personal - salarii datorate", "423": "Personal - ajutoare materiale datorate",
    "425": "Avansuri acordate personalului", "426": "Drepturi de personal neridicate",
    "427": "Rețineri din salarii datorate terților",
    "428": "Alte datorii și creanțe în legătură cu personalul",
    "431": "Asigurări sociale", "4315": "Contribuția de asigurări sociale",
    "4316": "Contribuția de asigurări sociale de sănătate",
    "436": "Contribuția asiguratorie pentru muncă",
    "437": "Ajutor de șomaj", "438": "Alte datorii și creanțe sociale",
    "441": "Impozitul pe profit și alte impozite", "4411": "Impozitul pe profit",
    "4418": "Impozitul pe venit",
    "442": "Taxa pe valoarea adăugată", "4423": "TVA de plată", "4424": "TVA de recuperat",
    "4426": "TVA deductibilă", "4427": "TVA colectată", "4428": "TVA neexigibilă",
    "444": "Impozitul pe venituri de natura salariilor",
    "445": "Subvenții", "446": "Alte impozite, taxe și vărsăminte asimilate",
    "447": "Fonduri speciale - taxe și vărsăminte asimilate",
    "448": "Alte datorii și creanțe cu bugetul statului",
    "455": "Sume datorate acționarilor/asociaților",
    "4551": "Acționari/asociați - conturi curente",
    "456": "Decontări cu acționarii/asociații privind capitalul",
    "457": "Dividende de plată", "458": "Decontări din operațiuni în participație",
    "461": "Debitori diverși", "462": "Creditori diverși",
    "471": "Cheltuieli înregistrate în avans", "472": "Venituri înregistrate în avans",
    "473": "Decontări din operațiuni în curs de clarificare",
    "491": "Ajustări pentru deprecierea creanțelor - clienți",
    "5121": "Conturi la bănci în lei", "5124": "Conturi la bănci în valută",
    "5125": "Sume în curs de decontare", "512": "Conturi curente la bănci",
    "518": "Dobânzi", "519": "Credite bancare pe termen scurt",
    "531": "Casa", "5311": "Casa în lei", "5314": "Casa în valută",
    "532": "Alte valori", "5328": "Alte valori",
    "541": "Acreditive", "542": "Avansuri de trezorerie",
    "581": "Viramente interne",
    "601": "Cheltuieli cu materiile prime", "602": "Cheltuieli cu materialele consumabile",
    "6021": "Cheltuieli cu materialele auxiliare", "6022": "Cheltuieli privind combustibilii",
    "6024": "Cheltuieli privind piesele de schimb", "6028": "Cheltuieli privind alte materiale consumabile",
    "603": "Cheltuieli privind materialele de natura obiectelor de inventar",
    "604": "Cheltuieli privind materialele nestocate",
    "605": "Cheltuieli privind utilitățile", "607": "Cheltuieli privind mărfurile",
    "608": "Cheltuieli privind ambalajele",
    "611": "Cheltuieli cu întreținerea și reparațiile",
    "612": "Cheltuieli cu redevențele, locațiile de gestiune și chiriile",
    "613": "Cheltuieli cu primele de asigurare", "614": "Cheltuieli cu studiile și cercetările",
    "621": "Cheltuieli cu colaboratorii", "622": "Cheltuieli privind comisioanele și onorariile",
    "623": "Cheltuieli de protocol, reclamă și publicitate",
    "624": "Cheltuieli cu transportul de bunuri și personal",
    "625": "Cheltuieli cu deplasări, detașări și transferări",
    "626": "Cheltuieli poștale și taxe de telecomunicații",
    "627": "Cheltuieli cu serviciile bancare și asimilate",
    "628": "Alte cheltuieli cu serviciile executate de terți",
    "635": "Cheltuieli cu alte impozite, taxe și vărsăminte asimilate",
    "641": "Cheltuieli cu salariile personalului",
    "642": "Cheltuieli cu avantajele în natură și tichetele acordate salariaților",
    "645": "Cheltuieli privind asigurările și protecția socială",
    "646": "Cheltuieli privind contribuția asiguratorie pentru muncă",
    "652": "Cheltuieli cu protecția mediului înconjurător",
    "654": "Pierderi din creanțe și debitori diverși",
    "655": "Cheltuieli din reevaluarea imobilizărilor corporale",
    "658": "Alte cheltuieli de exploatare", "6581": "Despăgubiri, amenzi și penalități",
    "6588": "Alte cheltuieli de exploatare",
    "665": "Cheltuieli din diferențe de curs valutar", "666": "Cheltuieli privind dobânzile",
    "667": "Cheltuieli privind sconturile acordate",
    "681": "Cheltuieli de exploatare privind amortizările, provizioanele",
    "6811": "Cheltuieli de exploatare privind amortizarea imobilizărilor",
    "6812": "Cheltuieli de exploatare privind provizioanele",
    "6814": "Cheltuieli de exploatare privind ajustările pentru deprecierea activelor circulante",
    "691": "Cheltuieli cu impozitul pe profit", "698": "Cheltuieli cu impozitul pe venit",
    "701": "Venituri din vânzarea produselor finite", "704": "Venituri din servicii prestate",
    "705": "Venituri din studii și cercetări", "706": "Venituri din redevențe, locații de gestiune și chirii",
    "707": "Venituri din vânzarea mărfurilor", "708": "Venituri din activități diverse",
    "711": "Venituri aferente costurilor stocurilor de produse",
    "721": "Venituri din producția de imobilizări necorporale",
    "722": "Venituri din producția de imobilizări corporale",
    "741": "Venituri din subvenții de exploatare",
    "754": "Venituri din creanțe reactivate și debitori diverși",
    "758": "Alte venituri din exploatare", "7581": "Venituri din despăgubiri, amenzi și penalități",
    "7588": "Alte venituri din exploatare",
    "765": "Venituri din diferențe de curs valutar", "766": "Venituri din dobânzi",
    "767": "Venituri din sconturi obținute",
    "781": "Venituri din provizioane și ajustări pentru depreciere",
    "7814": "Venituri din ajustări pentru deprecierea activelor circulante",
    "8051": "Dobânzi de plătit",
    # OMFP 3103/2017 - persoane juridice fara scop patrimonial (grupa 73, verificat la sursa)
    "731": "Venituri din cotizațiile membrilor, contribuțiile bănești sau în natură ale membrilor și simpatizanților, din cote-părți primite potrivit statutului",
    "732": "Venituri din taxele de înregistrare stabilite potrivit legislației în vigoare",
    "733": "Venituri din donații, sume sau bunuri primite prin sponsorizare și ajutoare",
    "734": "Venituri financiare rezultate din activitățile fără scop patrimonial",
    "736": "Venituri din subvenții de exploatare",
    "738": "Alte venituri din activitățile fără scop patrimonial",
}


def denumire_omfp(cont):
    """Denumirea OMFP pentru un simbol de cont; cadere pe sinteticul de 3 cifre; '' daca necunoscut."""
    c = str(cont or "").strip()
    if c in PLAN_OMFP:
        return PLAN_OMFP[c]
    if len(c) > 3 and c[:4] in PLAN_OMFP:
        return PLAN_OMFP[c[:4]]
    if len(c) >= 3 and c[:3] in PLAN_OMFP:
        return PLAN_OMFP[c[:3]]
    return ""
