# -*- coding: utf-8 -*-
"""REGISTRUL STRATURILOR — singura sursă autoritativă pentru întrebarea „ce strat e modulul ăsta?".

DE CE EXISTĂ (P7 valul V3, 13.09.2026). Diagnosticul P7 a măsurat criteriul canonic *„un motor
fiscal nu importă `db`"* și a găsit **zero** încălcări — dar pe un univers derivat din DOUĂ
instrumente care nu cad de acord: generatoarele celor nouă declarații (25 de module) și modulele
care poartă valori fiscale (104). Șapte module cădeau între ele, iar pentru ele întrebarea nu se
putea decide. *Un criteriu al cărui univers nu e definit nu e o măsurătoare, e o aproximare.*

Registrul închide nedeterminarea: fiecare modul relevant are EXACT un strat, scris, cu motivul
mecanic lângă el și cu regula canonică pe care se sprijină.

CELE PATRU STRATURI sunt cele din `PLAN_HARDENING.md:842-846`, niciunul în plus:
  · **HTTP**          — validare de formă, autentificare, traducerea erorilor în coduri;
  · **USE_CASE**      — deține tranzacția (P4), orchestrează, fără reguli fiscale;
  · **FISCAL_ENGINE** — primește date, întoarce rezultat, nu deschide conexiuni;
  · **REPOSITORY**    — singurul care știe SQL și scheme.

## CE ÎNSEAMNĂ `mixt_cu`, și de ce nu e un al cincilea strat

Multe module fac azi două lucruri deodată — un motor fiscal care își citește singur datele, o rută
care scrie SQL. Comanda V3 e limpede: *„Dacă un modul combină efectiv două straturi și nu poate primi
onest un singur strat: NU inventa clasificarea."* Deci `strat` rămâne **responsabilitatea principală**
(una singură, niciodată două), iar `mixt_cu` numește al doilea strat pe care modulul îl atinge de
fapt. Un modul cu `mixt_cu` nu e o excepție tolerată: e o poziție de lucru pentru valul care separă.

**38 din 114** sunt mixte azi. Cifra nu se ascunde și nu se rotunjește.

## DE UNDE VINE FIECARE DECLARAȚIE

`motiv` e faptul mecanic măsurat la declarare (câte rute, câte instrucțiuni SQL, dacă importă `db`,
dacă e generator de declarație), iar `regula` e linia din textul canonic pe care se sprijină. Pentru
**29 de module** faptele mecanice nu ajungeau — acolo scrie *„citit la sursa"*, fiindcă le-am citit
și am decis, nu le-am derivat dintr-un nume de fișier.

## CE NU E REGISTRUL

Nu e generat la fiecare rulare: e **scris**. Un registru care s-ar regenera din euristici ar muta
autoritatea înapoi la euristică — exact ce V3 trebuia să elimine. Tabelul de mai jos a fost tastat o
dată cu ajutorul unui script, apoi verificat; de aici încolo, adevărul e ce scrie aici, iar
`scripts/scan_p7_straturi.py` îl **consumă**, nu îl recalculează.

UNIVERSUL (cine TREBUIE să fie în registru) se derivă însă mecanic, în afara fișierului ăstuia, și e
verificat de `core/test_p7_straturi.py`: reuniunea celor două definiții de „fiscal" plus modulele cu
rute, fără instrumentele de măsură și fără probe. Un modul nou care intră în univers fără declarație
**pică poarta** — registrul e exhaustiv față de UNIVERS, nu față de ziua în care a fost scris.
"""
import collections

HTTP = "HTTP"
USE_CASE = "USE_CASE"
FISCAL_ENGINE = "FISCAL_ENGINE"
REPOSITORY = "REPOSITORY"

#: Cele patru, în ordinea din textul canonic. Orice altă valoare e invalidă, iar o probă o cere.
STRATURI = (HTTP, USE_CASE, FISCAL_ENGINE, REPOSITORY)

D = collections.namedtuple("D", "cale strat mixt_cu motiv regula")

#: Felurile de declarație stricată — mulțime ÎNCHISĂ, ca o probă să întrebe codul, nu proza.
STRAT_NECUNOSCUT = "STRAT_NECUNOSCUT"
MIXT_NECUNOSCUT = "MIXT_NECUNOSCUT"
MIXT_CU_SINE = "MIXT_CU_SINE"
DUBLURA = "DUBLURA"
FARA_TEMEI = "FARA_TEMEI"

Invalid = collections.namedtuple("Invalid", "cale cod detaliu")

#: TUPLU, nu dicționar — deliberat, două motive: un tuplu e imutabil, deci nu intră în inventarul de
#: stare mutabilă al P6; și un dicționar ar ascunde o cale declarată de două ori, pe când aici
#: dublura rămâne vizibilă și o probă o caută.
REGISTRU = (
    D("core/amef_import.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/asistenti_api.py", REPOSITORY, None,
      "«managementul actorilor de cabinet» — operatii pe date, 25 de instructiuni SQL, nicio regula fiscala proprie",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/asociati_import_api.py", REPOSITORY, None,
      "import de asociati per firma; 4 SQL, zero calcul fiscal",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/audit_preluare.py", REPOSITORY, None,
      "«audit de PRELUARE firma» — citeste si scrie urme; 10 SQL",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/avansuri.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/bacsis.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/beneficii_api.py", FISCAL_ENGINE, None,
      "«beneficii extrasalariale ONE-OFF pe luna» — plafoane fiscale aplicate pe date; 0 instructiuni SQL — cele 6 au trecut la valul D4 in `core/repo_beneficii_api.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/bilant_api.py", REPOSITORY, None,
      "isi spune singur stratul: «S1005 - strat DB: solduri finale + rulaje din note VALIDATE, apoi core.bilant» — calculul e in `core/bilant.py`, aici e accesul la date",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/casa.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/cashflow.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/categorie_marime.py", FISCAL_ENGINE, None,
      "«Categoria de marime a entitatii» — incadrare pe praguri legale; 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_categorie_marime.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/common.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/comodat_chirii.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/contracte_speciale.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/control_fiscal_api.py", FISCAL_ENGINE, None,
      "«semafor de conformare fiscala per firma» — produce un verdict fiscal; 0 instructiuni SQL — cele 8 au trecut la valul D4 in `core/repo_control_fiscal_api.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/control_incrucisat.py", FISCAL_ENGINE, None,
      "«verificare INCRUCISATA declaratie vs contabilitate» — compara doua evidente dupa reguli fiscale; 0 instructiuni SQL — cele 45 au trecut la valul D4 in `core/repo_control_incrucisat.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/cor_api.py", REPOSITORY, None,
      "nomenclatorul COR — depozit de nomenclator; 5 SQL",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/cote_tva.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/curs_bnr.py", REPOSITORY, None,
      "«curs valutar BNR pentru facturi in valuta» — aduce si pastreaza cursuri, nu aplica o regula fiscala; valorile fiscale numarate de scan_constante sunt praguri de cache",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/d100.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 3 au trecut la valul D4 in `core/repo_d100.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d100_pozitia_116.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; zero SQL, zero db",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d100_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 2 au trecut la valul D4 in `core/repo_d100_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d101.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 5 au trecut la valul D4 in `core/repo_d101.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d101_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d101_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d101g.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d101g.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d104.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d104.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d108.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d112.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 3 au trecut la valul D4 in `core/repo_d112.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d112_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 6 au trecut la valul D4 in `core/repo_d112_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d120.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d169.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d169n.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d200.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d201.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d204.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d205.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 3 au trecut la valul D4 in `core/repo_d205.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d205_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 2 au trecut la valul D4 in `core/repo_d205_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d207.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d207.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d212.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d212_engine.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d213.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d214.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d216.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d220.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d220.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d221.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d221.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d223.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d223.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d230.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d300.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 8 au trecut la valul D4 in `core/repo_d300.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d300_manual_api.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 5 au trecut la valul D4 in `core/repo_d300_manual_api.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d300_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 2 au trecut la valul D4 in `core/repo_d300_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d301.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 2 au trecut la valul D4 in `core/repo_d301.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d301_operatiuni_api.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 4 au trecut la valul D4 in `core/repo_d301_operatiuni_api.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d301_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d301_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d318.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d390.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 12 au trecut la valul D4 in `core/repo_d390.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d390_clasificare_api.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 5 au trecut la valul D4 in `core/repo_d390_clasificare_api.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d390_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 5 au trecut la valul D4 in `core/repo_d390_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d394.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 4 au trecut la valul D4 in `core/repo_d394.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d394_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — singura a trecut la valul D4 in `core/repo_d394_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d397.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d398.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d399.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d401.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d402.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d403.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d406.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 9 au trecut la valul D4 in `core/repo_d406.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d406_active.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; zero SQL, zero db",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d406_reconciliere.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; 0 instructiuni SQL — cele 2 au trecut la valul D4 in `core/repo_d406_reconciliere.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d406_stocuri.py", FISCAL_ENGINE, None,
      "generator al uneia dintre cele noua declaratii; zero SQL, zero db",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d407.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d600.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d603.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/decontari_asociati.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/deconturi.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/duk.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/efactura_send.py", FISCAL_ENGINE, None,
      "«generator XML UBL 2.1 / CIUS-RO» — produce un document normat din date; 0 instructiuni SQL, zero db dupa valul D2",
      "PLAN_HARDENING.md:845 — un motor fiscal nu importa `db`"),
    D("core/efactura_trimitere.py", USE_CASE, None,
      "«trimiterea unei facturi in SPV» — orchestreaza cele patru porti si detine cele trei tranzactii; 0 instructiuni SQL, zero regula fiscala proprie",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/export_saga.py", REPOSITORY, None,
      "export de facturi catre alt program; 4 SQL, zero regula fiscala",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/factura_pdf.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/facturi_api.py", REPOSITORY, None,
      "«facturi in schema unui tenant: lista, creare, detalii, stergere» — CRUD; 19 SQL",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/firma_rezumat.py", REPOSITORY, None,
      "«MODELUL DE CITIRE al portofoliului» — P2; un read-model e prin definitie repository",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/import_export.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/intrastat.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/leasing.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/lichidare.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/monitor_fiscal.py", USE_CASE, None,
      "«cron saptamanal. Citeste noutatile ANAF/MF, AI filtreaza» — orchestreaza o munca de fundal si o persista; nu calculeaza nicio obligatie; 0 instructiuni SQL — cele 8 au trecut la valul D4 in `core/repo_monitor_fiscal.py`",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/motor.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/notificari_scadenta.py", USE_CASE, None,
      "«notificare email scadenta/restanta» — orchestreaza un efect extern peste date citite; pragul de zile e o regula de produs, nu o cota; 0 instructiuni SQL — cele 7 au trecut la valul D4 in `core/repo_notificari_scadenta.py`",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/obiecte_inventar.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/ong.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/perisabilitati.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/provizioane.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/registru_evidenta_fiscala.py", FISCAL_ENGINE, None,
      "registru fiscal: compune si persista randuri dupa norma; 0 instructiuni SQL — cele 3 au trecut la valul D4 in `core/repo_registru_evidenta_fiscala.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/registru_inventar.py", FISCAL_ENGINE, None,
      "«Registrul-inventar (cod 14-1-2)» — unul dintre cele trei registre obligatorii; 0 instructiuni SQL — cele 3 au trecut la valul D4 in `core/repo_registru_inventar.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/reverificare.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/salariati_api.py", REPOSITORY, None,
      "«salariati in schema unui tenant: lista, creare, detalii» — CRUD; 21 SQL",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/salariati_import_api.py", REPOSITORY, None,
      "import de salariati per firma; 4 SQL",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/salarii_contare.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/salarizare.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/scadentar.py", FISCAL_ENGINE, None,
      "«scadentar facturi emise neincasate» — clasificare pe praguri de zile. ATENTIE: docstringul spune «Calcul PUR, fara DB», dar modulul are `pull`/`seteaza_optin`/`seteaza_supapa` cu — proza descrie doar miezul pur (clasa R16). Consemnat, NEreparat aici; 0 instructiuni SQL — cele 5 au trecut la valul D4 in `core/repo_scadentar.py`",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/scadente.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/sponsorizari.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/spv_rute.py", HTTP, None,
      "3 rute montate in modul",
      "PLAN_HARDENING.md:839 — stratul HTTP e acolo unde sunt rutele"),
    D("core/stare_partajata.py", REPOSITORY, None,
      "«starea business care nu mai are voie sa traiasca in memoria unui proces» (P6 valul 1) — esecuri de autentificare si cooldown de alerte; nicio regula fiscala",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/stat_plata_api.py", REPOSITORY, None,
      "acces la statele de plata; 3 SQL, calculul e in `salarizare`",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/stat_plata_emis.py", REPOSITORY, None,
      "«statul de plata ca DOCUMENT EMIS, nu ca vedere recalculata» — pastreaza documentul emis",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/stocuri.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/taxare_inversa.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/termene_api.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/tva_agricultori.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/tva_aur.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/tva_incasare.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/tva_marja.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/tva_marja_turism.py", FISCAL_ENGINE, None,
      "poarta valori fiscale (scan_constante); zero SQL, zero db — pur prin constructie",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/repo_admin.py", REPOSITORY, None,
      "P7 · V1: panoul de administrare: sănătate, activitate, anunțuri, evenimente publice — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_banca.py", REPOSITORY, None,
      "P7 · V2: extrasul de cont si liniile lui — scrieri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/tranzactie.py", USE_CASE, None,
      "P7 · V2: cele zece instructiuni de control de tranzactie (SAVEPOINT, SET LOCAL search_path) "
      "scoase din stratul HTTP. NU detine tranzactia: executa pe cursorul primit, la acelasi loc",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/repo_casa.py", REPOSITORY, None,
      "P7 · V1: casa: bonuri și chitanțe — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_contabilitate.py", REPOSITORY, None,
      "P7 · V1: notele contabile, planul de conturi, perioadele blocate — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_declaratii.py", REPOSITORY, None,
      "P7 · V1: coada declarațiilor și artefactele lor — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_efactura.py", REPOSITORY, None,
      "P7 · V1: e-Factura primită și trimiterile către SPV — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_facturi.py", REPOSITORY, None,
      "P7 · V1: facturile din schema unui tenant — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_firma_profil.py", REPOSITORY, None,
      "P7 · V1: profilul firmei din schema ei — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_mijloace_fixe.py", REPOSITORY, None,
      "P7 · V1: mijloacele fixe din schema unui tenant — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_portal.py", REPOSITORY, None,
      "P7 · V1: portalul clientului: solicitări și clienți — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_salariati.py", REPOSITORY, None,
      "P7 · V1: salariații și cheile REGES — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_stocuri.py", REPOSITORY, None,
      "P7 · V1: articolele și mișcările de stoc — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_tenants.py", REPOSITORY, None,
      "P7 · V1: firmele din portofoliu și cabinetele lor — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_utilizatori.py", REPOSITORY, None,
      "P7 · V1: conturile și accesul clienților — citiri mutate din rute, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("main.py", HTTP, None,
      "421 rute montate in modul si 0 instructiuni SQL — dupa V1+V2 niciuna nu mai statea in corpul unei rute, iar valul D4 le-a scos si pe ultimele 38 din helperii de modul, in `core/repo_main.py`",
      "PLAN_HARDENING.md:839 — stratul HTTP e acolo unde sunt rutele"),
    D("core/repo_beneficii_api.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/beneficii_api.py` — 6 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_categorie_marime.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/categorie_marime.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_control_fiscal_api.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/control_fiscal_api.py` — 8 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_control_incrucisat.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/control_incrucisat.py` — 45 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d100.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d100.py` — 3 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d100_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d100_reconciliere.py` — 2 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d101.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d101.py` — 5 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d101_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d101_reconciliere.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d101g.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d101g.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d104.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d104.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d112.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d112.py` — 3 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d112_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d112_reconciliere.py` — 6 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d205.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d205.py` — 3 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d205_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d205_reconciliere.py` — 2 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d207.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d207.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d220.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d220.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d221.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d221.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d223.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d223.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d300.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d300.py` — 8 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d300_manual_api.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d300_manual_api.py` — 5 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d300_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d300_reconciliere.py` — 2 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d301.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d301.py` — 2 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d301_operatiuni_api.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d301_operatiuni_api.py` — 4 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d301_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d301_reconciliere.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d390.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d390.py` — 12 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d390_clasificare_api.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d390_clasificare_api.py` — 5 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d390_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d390_reconciliere.py` — 5 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d394.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d394.py` — 4 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d394_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d394_reconciliere.py` — 1 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d406.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d406.py` — 9 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_d406_reconciliere.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/d406_reconciliere.py` — 2 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_main.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `main.py` — 38 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_monitor_fiscal.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/monitor_fiscal.py` — 8 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_notificari_scadenta.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/notificari_scadenta.py` — 7 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_registru_evidenta_fiscala.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/registru_evidenta_fiscala.py` — 3 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_registru_inventar.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/registru_inventar.py` — 3 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/repo_scadentar.py", REPOSITORY, None,
      "P7 · valul D4: SQL-ul lui `core/scadentar.py` — 5 instructiuni SQL, zero `get_conn`, zero commit",
      "PLAN_HARDENING.md:842 — repository-ul e singurul care stie SQL si scheme"),
    D("core/erori.py", USE_CASE, None,
      "P7 · valul use-case: vocabularul de refuz al stratului use-case; 0 instructiuni SQL, zero dependente — traducerea in coduri HTTP sta in `main.py`",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_admin.py", USE_CASE, None,
      "P7 · valul use-case: 10 functii mutate din `main.py`, 11 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_api.py", USE_CASE, None,
      "P7 · valul use-case: 6 functii mutate din `main.py`, 6 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_asistenti.py", USE_CASE, None,
      "P7 · valul use-case: 15 functii mutate din `main.py`, 15 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_auth.py", USE_CASE, None,
      "P7 · valul use-case: 2 functii mutate din `main.py`, 4 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_cabinet.py", USE_CASE, None,
      "P7 · valul use-case: 4 functii mutate din `main.py`, 5 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_capacitate.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_coada.py", USE_CASE, None,
      "P7 · valul use-case: 6 functii mutate din `main.py`, 14 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_comun.py", USE_CASE, None,
      "P7 · valul use-case: 60 functii mutate din `main.py`, 14 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_cont.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_control_fiscal.py", USE_CASE, None,
      "P7 · valul use-case: 3 functii mutate din `main.py`, 6 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_cor.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_declaratii.py", USE_CASE, None,
      "P7 · valul use-case: 3 functii mutate din `main.py`, 5 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_eu.py", USE_CASE, None,
      "P7 · valul use-case: 14 functii mutate din `main.py`, 14 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_firme.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_firme_scoase.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_gdpr.py", USE_CASE, None,
      "P7 · valul use-case: 4 functii mutate din `main.py`, 4 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_migrare.py", USE_CASE, None,
      "P7 · valul use-case: 4 functii mutate din `main.py`, 5 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_notificari.py", USE_CASE, None,
      "P7 · valul use-case: 5 functii mutate din `main.py`, 5 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_pachete.py", USE_CASE, None,
      "P7 · valul use-case: 6 functii mutate din `main.py`, 10 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_portal.py", USE_CASE, None,
      "P7 · valul use-case: 22 functii mutate din `main.py`, 27 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_public.py", USE_CASE, None,
      "P7 · valul use-case: 6 functii mutate din `main.py`, 9 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_raportari.py", USE_CASE, None,
      "P7 · valul use-case: 10 functii mutate din `main.py`, 10 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_recomanda.py", USE_CASE, None,
      "P7 · valul use-case: 2 functii mutate din `main.py`, 2 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_supervizor.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 2 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_tenants.py", USE_CASE, None,
      "P7 · valul use-case: 254 functii mutate din `main.py`, 277 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_termene.py", USE_CASE, None,
      "P7 · valul use-case: 1 functii mutate din `main.py`, 1 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),
    D("core/uc_tipare.py", USE_CASE, None,
      "P7 · valul use-case: 2 functii mutate din `main.py`, 2 tranzactii proprii, 0 instructiuni SQL",
      "PLAN_HARDENING.md:840 — use-case-ul detine tranzactia si orchestreaza"),

    # ── [E2a, 15.09.2026] Universul, nu esantionul ──────────────────
    # Pana azi registrul acoperea DOUA definitii de „fiscal" plus modulele cu rute. E2a il
    # largeste la intrebarea care conteaza: ORICE modul al aplicatiei care contine SQL. Cele
    # 51 de migrari unice (`core/migrare_*.py`) raman in afara, intr-o clasa NUMITA, nu tacut.
    D("core/adeverinta.py", REPOSITORY, None,
      "«F136: adeverinta de salariat (generica), PDF» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/ai_incredere.py", REPOSITORY, None,
      "«Incredere + invatare pentru propunerile AI» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/alerta_acces.py", REPOSITORY, None,
      "«GDPR art.33 (pregatire) — alerta acces anormal pe public.audit_log» — acces la date; 2 get_conn / 0 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/alerte_control_fiscal.py", REPOSITORY, None,
      "«stratul pull->push al controlului fiscal» — acces la date; 3 get_conn / 0 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/api_public.py", REPOSITORY, None,
      "«API public: chei per cabinet» — acces la date; 0 get_conn / 3 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/artefacte.py", REPOSITORY, None,
      "«R45: locul UNIC in care se pastreaza un artefact produs» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/articole_import_api.py", REPOSITORY, None,
      "«import articole + stoc initial CV (F151) per firma» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/audit_retentie.py", REPOSITORY, None,
      "«GDPR art.5 minimizare — retentie pe public.audit_log» — acces la date; 1 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/audit_schema.py", REPOSITORY, None,
      "«F165: auditor de conformitate a schemelor tenant vs tenant_template.sql» — acces la date; 1 get_conn / 0 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/auth_api.py", REPOSITORY, None,
      "«autentificare API: login, register, context token, acces tenant» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/capacitate_api.py", REPOSITORY, None,
      "«panou Capacitate pentru patron (admin_firma)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/casa_api.py", REPOSITORY, None,
      "«Registru de casă — API» — acces la date; 0 get_conn / 2 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/centre_cost_api.py", REPOSITORY, None,
      "«nomenclator centre de cost (F143 Faza 1)» — acces la date; 0 get_conn / 3 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/clasificator_alerte.py", FISCAL_ENGINE, None,
      "eticheta unei alerte devine o PREDICTIE confruntabila: rezultatul e calculul, nu randul",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/clienti_api.py", REPOSITORY, None,
      "«clienți/parteneri în schema unui tenant: listă, creare, detalii, editare, ștergere» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/coada_api.py", REPOSITORY, None,
      "«coada de validare a declarațiilor (public.declaratii_coada)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/cont_valid.py", FISCAL_ENGINE, None,
      "confrunta un cont din corpul cererii cu planul firmei — regula de validare, cu o citire",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/contare_facturi.py", FISCAL_ENGINE, None,
      "«CONTAREA UNEI FACTURI — un adevar, un loc (P1)»: regula de contare e continutul modulului; cele 15 instructiuni sunt citirile de care are nevoie",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/contracte_api.py", REPOSITORY, None,
      "«F147: generare contracte din sabloane (mail-merge)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/cron.py", USE_CASE, None,
      "ambalajul joburilor de fundal: deschide conexiuni si conduce pasii",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/d106.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d107.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d110.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d177.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d307.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d311.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/d710.py", FISCAL_ENGINE, None,
      "generator de declaratie; pull-ul propriu atinge si depozitul (v. D4b)",
      "PLAN_HARDENING.md:841 — motorul fiscal primeste date si intoarce rezultat"),
    D("core/declaratii_api.py", USE_CASE, None,
      "dispatch pentru TOATE declaratiile: alege generatorul si duce cererea la el",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/documente_api.py", REPOSITORY, None,
      "acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/echilibru_perioada.py", FISCAL_ENGINE, None,
      "partida dubla verificata pe perioada: o regula de integritate, nu un depozit",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/etransport_send.py", USE_CASE, None,
      "trimiterea UIT prin API OAuth: orchestrare cu stare proprie",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/facturi_recurente.py", USE_CASE, None,
      "cron care EMITE facturi din sabloane: orchestrare cu tranzactii proprii",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/firma_profil_api.py", REPOSITORY, None,
      "«profilul firmei din schema unui tenant» — acces la date; 0 get_conn / 3 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/fisa_cont.py", REPOSITORY, None,
      "«Fisa de cont pentru operatiuni diverse (cod 14-6-22)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/gdpr_cerere.py", REPOSITORY, None,
      "«GDPR art.17 — cererea de stergere DEPUSA de cabinet (NU executa nimic)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/gdpr_sterge.py", USE_CASE, None,
      "EXECUTA stergerea GDPR (13 instructiuni, commit propriu): act, nu depozit",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/inchidere_luna.py", USE_CASE, None,
      "«ACTUL DE INCHIDERE a lunii»: un act care orchestreaza, nu o citire",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/instante.py", REPOSITORY, None,
      "«P6 valul 3 — mai multe procese care servesc, fara ca vreunul sa creada ca e singur» — acces la date; 1 get_conn / 0 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/istoric_declaratii_import_api.py", REPOSITORY, None,
      "«import istoric declaratii (stratul 7) per firma» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/jurnal_api.py", REPOSITORY, None,
      "«Jurnal — editare/ștergere/validare note» — acces la date; 0 get_conn / 4 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/mijloace_fixe_import_api.py", REPOSITORY, None,
      "«import mijloace fixe (stratul 6 migrare) per firma» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/notificari_api.py", REPOSITORY, None,
      "«notificari in-app (clopotel)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/pachete_api.py", REPOSITORY, None,
      "«Pachetul lunar / 'Povestea lunii'» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/perioada.py", REPOSITORY, None,
      "«starea CONFIRMAT/NECONFIRMAT a unei perioade (an, luna, domeniu)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/plata_salarii.py", REPOSITORY, None,
      "«[F134 step 2] fisierul de plata a salariilor pe card» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/plati.py", REPOSITORY, None,
      "«Calea de plata online — INCHISA» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/pontaj.py", REPOSITORY, None,
      "«F135: pontaj lunar informativ per salariat» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/portal_api.py", REPOSITORY, None,
      "«portalul clientului (rol 'client'), READ-ONLY» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/produse_api.py", REPOSITORY, None,
      "«nomenclatorul de produse per firma (schema tenant)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/rapoarte_comerciale_api.py", REPOSITORY, None,
      "«F144 v1: rapoarte comerciale READ-ONLY» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/raport_z.py", REPOSITORY, None,
      "«unicitatea raportului Z, mutată din COD în BAZĂ» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/raportari_api.py", REPOSITORY, None,
      "«canal de feedback: cei care proceseaza trimit raportari catre Admin iConta; raspunsurile vin inapoi in firul f» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/reconciliere_api.py", REPOSITORY, None,
      "«Reconciliere bancară — strat API (tipar stat_plata_api: funcții conn+schema)» — acces la date; 0 get_conn / 3 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/registratura_api.py", REPOSITORY, None,
      "«F146: registratura documente (registru unic intrare-iesire)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/reset_parola.py", REPOSITORY, None,
      "«recuperare parola cont CABINET ('Am uitat parola')» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/retete_api.py", REPOSITORY, None,
      "«Retetar - strat DB» — acces la date; 0 get_conn / 3 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/retete_import_api.py", REPOSITORY, None,
      "«import retete HoReCa (F150) per firma» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/rip_api.py", REPOSITORY, None,
      "«Registru-jurnal de încasări și plăți (OMFP 170/2015) + Fișa calcul D212» — acces la date; 0 get_conn / 5 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/rip_migrare_api.py", REPOSITORY, None,
      "«import registru încasări-plăți (RIP) la preluarea unui PFA» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/salariu_istoric.py", REPOSITORY, None,
      "«istoricul salariului de baza pe contract (PASUL 2, forma 1)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/sinteza_zilnica.py", REPOSITORY, None,
      "«sinteza zilnica a activitatii din cabinet, trimisa seara patronului (admin_firma) pe email-ul de login» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/solduri_api.py", REPOSITORY, None,
      "«import solduri inițiale (balanță de deschidere) per firmă» — acces la date; 0 get_conn / 2 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/solduri_parteneri_api.py", REPOSITORY, None,
      "«import solduri parteneri (defalcare 4111/401 per client/furnizor)» — acces la date; 0 get_conn / 2 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/sonda_scrieri.py", REPOSITORY, None,
      "«cine scrie in `salariu_istoric`, si daca scrierea a RAMAS» — acces la date; 0 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/sonda_web.py", REPOSITORY, None,
      "«R75, varianta (b): procesul care servește ecranele intră în deadman» — acces la date; 2 get_conn / 1 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/spv_conector.py", USE_CASE, None,
      "conectorul UNIC SPV/ANAF: orchestreaza OAuth + apelurile, cu tranzactii proprii",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/spv_poll.py", USE_CASE, None,
      "cron de POLL e-Factura: conduce pasii",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/spv_receive.py", USE_CASE, None,
      "cron RECEIVE e-Factura: conduce pasii",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/spv_refresh.py", REPOSITORY, None,
      "«driver cron pentru refresh-ul token-urilor SPV (F177)» — acces la date; 1 get_conn / 0 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/stocuri_api.py", REPOSITORY, None,
      "«Stocuri global-valorică — strat API» — acces la date; 0 get_conn / 2 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/stocuri_cv_api.py", REPOSITORY, None,
      "«Stocuri cantitativ-valorice — strat API» — acces la date; 0 get_conn / 7 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/supervizor.py", USE_CASE, None,
      "«confruntarea incrucisata ca functionalitate distincta»: conduce comparatiile",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/supervizor_cache.py", REPOSITORY, None,
      "«rezultatul supervizorului, calculat o dată și citit ieftin» — acces la date; 4 get_conn / 2 commit proprii — atinge orchestrarea (D4b)",
      "citit la sursa (docstring + ce face modulul)"),
    D("core/tenant_provisioning.py", REPOSITORY, None,
      "«creează un tenant nou: schemă PostgreSQL + cele 21 de tabele (din template) + rândul în public.tenants + legar» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/tenant_stergere.py", REPOSITORY, None,
      "«R72: o firmă adăugată din greșeală se scoate; una cu evidență, nu» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/tipare_api.py", REPOSITORY, None,
      "«Ecran G: Educatie pe tipare (statistic, fara AI)» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/vector_fiscal_api.py", REPOSITORY, None,
      "«vectorul fiscal al unei firme» — acces la date",
      "PLAN_HARDENING.md:842 — depozitul e singurul care stie SQL si scheme"),
    D("core/woocommerce.py", USE_CASE, None,
      "conector care importa comenzi si emite facturi: orchestrare intre doua lumi",
      "citit la sursa (docstring + ce face modulul)"),

)


def pe_cale():
    """{cale: D} — construit la apel, nu ținut la nivel de modul (v. nota de la `REGISTRU`)."""
    return {d.cale: d for d in REGISTRU}


def strat(cale):
    """Stratul declarat, sau `None` dacă modulul nu e în registru. Fără implicit: absența se vede."""
    return pe_cale().get(cale, D(cale, None, None, "", "")).strat


def module_din_strat(s):
    """Căile declarate în stratul `s`. Asta consumă detectorul D2 — nicio altă definiție."""
    return {d.cale for d in REGISTRU if d.strat == s}


def mixte():
    """[D] — modulele care ating două straturi. Poziții de lucru pentru valul care separă."""
    return [d for d in REGISTRU if d.mixt_cu]


def declaratii_invalide(registru=None):
    """[(cale, motiv)] — tot ce ar face registrul de necrezut, într-un singur loc.

    Trei feluri, toate cerute de contractul V3: un strat care nu e dintre cele patru · aceeași cale
    declarată de două ori · o declarație fără motiv sau fără regulă (o clasificare fără temei e o
    părere, nu o declarație).
    """
    rele, vazute = [], set()
    for d in (REGISTRU if registru is None else registru):
        if d.strat not in STRATURI:
            rele.append(Invalid(d.cale, STRAT_NECUNOSCUT, repr(d.strat)))
        if d.mixt_cu is not None and d.mixt_cu not in STRATURI:
            rele.append(Invalid(d.cale, MIXT_NECUNOSCUT, repr(d.mixt_cu)))
        if d.mixt_cu == d.strat:
            rele.append(Invalid(d.cale, MIXT_CU_SINE, repr(d.strat)))
        if d.cale in vazute:
            rele.append(Invalid(d.cale, DUBLURA, "a doua declaratie pentru aceeasi cale"))
        vazute.add(d.cale)
        if not (d.motiv or "").strip() or not (d.regula or "").strip():
            rele.append(Invalid(d.cale, FARA_TEMEI, "motiv sau regula lipsa"))
    return rele


def numaratori():
    """Cifrele registrului, într-un singur loc, ca raportul să nu le recalculeze cu altă definiție."""
    pe_strat = collections.Counter(d.strat for d in REGISTRU)
    return {
        "MODULE_DECLARATE": len(REGISTRU),
        "MULTI_LAYER_MODULES": len([1 for x in declaratii_invalide() if x.cod == DUBLURA]),
        "UNKNOWN_LAYER_MODULES": len([1 for x in declaratii_invalide()
                                      if x.cod in (STRAT_NECUNOSCUT, MIXT_NECUNOSCUT)]),
        "MIXED_LAYER_MODULES": len(mixte()),
        "pe_strat": dict(pe_strat),
    }


def main():
    n = numaratori()
    print("REGISTRUL STRATURILOR")
    print("  module declarate     : %d" % n["MODULE_DECLARATE"])
    for s in STRATURI:
        print("    %-14s %d" % (s, n["pe_strat"].get(s, 0)))
    print("  mixte (doua straturi): %d" % n["MIXED_LAYER_MODULES"])
    for d in mixte()[:5]:
        print("    %s  %s + %s" % (d.cale, d.strat, d.mixt_cu))
    print("  declaratii invalide  : %d" % len(declaratii_invalide()))
    for x in declaratii_invalide():
        print("    %s: %s (%s)" % (x.cale, x.cod, x.detaliu))
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
